# Generated by Django 5.0.3 on 2025-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('Service', models.CharField(choices=[('Market', 'Market'), ('Loan Security', 'Loan Security'), ('Rental', 'Rental'), ('Deal Advisory', 'Deal Advisory'), ('Insurance', 'Insurance'), ('Investment', 'Investment'), ('Legal & Tax', 'Legal & Tax')], max_length=64, null=True)),
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Site_Address', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
