# Generated by Django 5.0.3 on 2025-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='type_of_property',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Office', 'Office'), ('Farm', 'Farm'), ('Vacant Land', 'Vacant Land'), ('Specialised', 'Specialised')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='Service',
            field=models.CharField(choices=[('Property', 'Property'), ('Loan Security', 'Loan Security'), ('Rental', 'Rental'), ('Deal Advisory', 'Deal Advisory'), ('Insurance', 'Insurance'), ('Investment', 'Investment'), ('Legal & Tax', 'Legal & Tax')], max_length=64, null=True),
        ),
    ]
